package kivik

// Error represents an error returned by Kivik.
type Error struct {
	// HTTPStatus is the HTTP status code associated with this error. Normally
	// this is the actual HTTP status returned by the server, but in some cases
	// it may be generated by Kivik directly. Check the FromServer value if
	// the distinction matters to you.
	HTTPStatus int

	// FromServer is set to true if the error was returned by the server.
	FromServer bool

	// Err is the originating error.
	Err error
}

var _ error = &Error{}
var _ statusCoder = &Error{}
var _ causer = &Error{}

func (e *Error) Error() string {
	return e.Err.Error()
}

// StatusCode returns the HTTP status code associated with the error, or 500
// (internal server error), if none.
func (e *Error) StatusCode() int {
	if e.HTTPStatus == 0 {
		return StatusInternalServerError
	}
	return e.HTTPStatus
}

// Cause satisfies the github.com/pkg/errors.causer interface by returning e.Err.
func (e *Error) Cause() error {
	return e.Err
}

type statusCoder interface {
	StatusCode() int
}

type causer interface {
	Cause() error
}

// StatusCode returns the HTTP status code embedded in the error, or 500
// (internal server error), if there was no specified status code.  If err is
// nil, StatusCode returns 0. This provides a convenient way to determine the
// precise nature of a Kivik-returned error.
//
// For example, to panic for all but NotFound errors:
//
//  err := db.Get(context.TODO(), "docID").ScanDoc(&doc)
//  if kivik.StatusCode(err) == kivik.StatusNotFound {
//      return
//  }
//  if err != nil {
//      panic(err)
//  }
//
// This method uses the statusCoder interface, which is not exported by this
// package, but is considered part of the stable public API.  Driver
// implementations are expected to return errors which conform to this
// interface.
//
//  type statusCoder interface {
//      StatusCode() int
//  }
func StatusCode(err error) int {
	if err == nil {
		return 0
	}
	if coder, ok := err.(statusCoder); ok {
		return coder.StatusCode()
	}
	return StatusInternalServerError
}
