stages:
    - test

variables:
    GO111MODULE: "on"

.test: &test_template
    stage: test
    script:
        - go mod download
        - go test -race -tags=livetest ./...

lint:
    stage: test
    image: golangci/golangci-lint:v1.55.2
    script:
        - go mod download
        - golangci-lint run ./...

coverage:
    stage: test
    image: golang:1.21
    script:
        - go mod download
        - ./script/coverage.sh

go-1.17:
    <<: *test_template
    image: golang:1.17

go-1.18:
    <<: *test_template
    image: golang:1.18

go-1.19:
    <<: *test_template
    image: golang:1.19

go-1.20:
    <<: *test_template
    image: golang:1.20

go-1.21:
    <<: *test_template
    image: golang:1.21
