[run]
timeout = "300s"

[[output.formats]]
format = "colored-line-number"

[linters]
enable = [
    "gci",
    "unconvert",
    "goimports",
    "unused",
    "misspell",
    "nakedret",
    "errcheck",
    "revive",
    "ineffassign",
    "unparam",
    "gofumpt",
    "govet",
    "prealloc",
    "gocritic",
    "staticcheck",
    "goheader",

    # SQL-related linters
    "rowserrcheck",
    "sqlclosecheck",
]

[issues]
exclude-use-default = false

[[issues.exclude-rules]]
source = "defer .*\\.(Close|Rollback)\\(\\)$"
linters = ["errcheck"]

[linters-settings.gci]
sections = ["standard", "default", "prefix(github.com/go-kivik/kivik)"]
skip-generated = false
custom-order = true

[linters-settings.goheader]
template = """
Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

 http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License."""

# Prepared statements on transactions are closed by the transaction.
[[issues.exclude-rules]]
source = "tx.Prepare|stmts.prepare"
linters = ["sqlclosecheck"]
