name: goreleaser check

on:
  pull_request:

jobs:
  check-goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"

      - name: Run goreleaser check
        uses: goreleaser/goreleaser-action@v5
        with:
          args: check
