name: Tests

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    name: Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.17", "1.18", "1.19", "1.20", "1.21", "1.22", "1.23", "1.24"]
    
    env:
      USETC: "1"

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -race -shuffle=on ./...
