name: Test x/sqlite

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test-x-sqlite:
    name: Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22, 1.23, 1.24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        working-directory: x/sqlite
        run: |
          go mod download
          go test -race -shuffle=on ./...
