name: tests-sqlite

on:
  pull_request:

jobs:
  golangcilint:
    strategy:
      matrix:
        go-version: [1.22] # TODO: Add 1.23rc2
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: |
          cd x/sqlite
          go mod download
          go test -race -shuffle=on ./...
