name: tests-sqlite

on:
  pull_request:

jobs:
  golangcilint:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Run tests
        run: |
          cd x/sqlite
          go mod download
          go test -race -shuffle=on ./...
